#!/bin/bash

# Define color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# This is a bash script that builds, runs tests, packs the package,
# and copies it to the test project as a dependency if all previous steps are successful.

DEST_DIR="/Users/becaye/PROJECTS/npm-tester/node_modules"
NEW_DIR="${DEST_DIR}/@becaaye/gbfs-system"

set -e # Exit immediately if a command exits with a non-zero status.

# Function to display messages in green
echo_success() {
    echo -e "${GREEN}$1${NC}"
    echo
}

# Function to display messages in yellow
echo_warning() {
    echo -e "${YELLOW}$1${NC}"
    echo
}

# Function to display messages in red
echo_error() {
    echo -e "${RED}$1${NC}"
    echo
}

echo_warning "Building package..."
npm run build && echo_success "Build successful."

# echo_warning "Running tests..."
# npm test && echo_success "Tests passed."

echo_warning "Cleaning up old package files in current project..."
rm -f *.tgz && echo_success "old package files cleaned"

echo_warning "Creating package..."
PACKAGE_FILE=$(npm pack | tail -n1) && echo_success "Package $PACKAGE_FILE created."

echo_warning "Cleaning up old package files in destination project..."
rm -rf "${DEST_DIR}/@becaaye" && echo_success "old package files cleaned in destination directory"

if [ -f "$PACKAGE_FILE" ]; then
    echo_warning "Creating package directory inside node_modules..."
    mkdir -p "${NEW_DIR}" && echo_success "Package destination directory created."

    echo_warning "Copying package..."
    cp "$PACKAGE_FILE" "$NEW_DIR" && echo_success "Package copied successfully."

    echo_warning "Unzipping copied package..."
    tar -xzf "${NEW_DIR}/${PACKAGE_FILE}" -C "$NEW_DIR" --strip-components=1 && echo_success "Package unzipped successfully."

    echo_warning "Cleaning package directory..."
    find "${NEW_DIR}" -name "*.tgz" -exec rm {} \; && echo_success "OPERATION COMPLETED !"
else
    echo_error "Error: Package file does not exist."
    exit 1
fi
