name: Release

on:
  pull_request:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: latest
      - run: npm ci
      - run: npm run build
      - run: npm run semantic-release
      - run: rm -rf node_modules
      - uses: ./dist 
